AUTHOR_FB: "https://facebook.com/sontran.ds"
GITHUB_REPO: "https://github.com/tdson/fels_203"
MESSAGE_TYPES: {success: "success", danger: "danger", info: "info", warning: "warning"}
user_per_page: 30
avatar_default: "default_avatar.png"
avatar_default_size: 80
avatar_medium: 100
avatar_large: 120
avatar_small: 50
category_per_page: 6
category_default_thumbnail: "default_category.jpg"
limit_category_name: 40
word_per_lesson: 5
activities_per_page: 20
admin:
  category_per_page: 20
  image_accepted_formats: "image/jpeg,image/gif,image/png"
  resize_image: 400
  user_per_page: 20
  word_per_page: 20
  max_meanings: 6
  min_meanings: 2
  allow_correct_meaning: 1
